name: vin-audit-website
services:
- environment_slug: node-js
  github:
    branch: main
    deploy_on_push: true
    repo: your-username/vin-audit-website
  name: web
  run_command: npm start
  source_dir: /
  http_port: 3000
  instance_count: 1
  instance_size_slug: basic-xxs
  routes:
  - path: /
  build_command: npm run build

# For static site deployment (recommended for this project):
# Uncomment the section below and comment out the section above
# 
# static_sites:
# - name: vin-audit-static
#   github:
#     branch: main
#     deploy_on_push: true
#     repo: your-username/vin-audit-website
#   source_dir: /
#   build_command: npm run build
#   output_dir: /out
#   routes:
#   - path: /